# Generated by Django 5.1.6 on 2025-02-28 20:52

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sala',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('Desocupada', 'Desocupada'), ('Ocupada', 'Ocupada'), ('Inhabilitada', 'Inhabilitada')], default='Desocupada', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('rut', models.CharField(max_length=12, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('estado', models.CharField(choices=[('Presente', 'Presente'), ('Con Permiso', 'Con Permiso'), ('Con Licencia Médica', 'Con Licencia Médica')], default='Presente', max_length=20)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AccesoSala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave_acceso', models.CharField(max_length=50)),
                ('fecha_asignacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_reserva', models.DateField()),
                ('bloque_horario', models.CharField(choices=[('1', 'Bloque 1 (8:15-9:00)'), ('2', 'Bloque 2 (9:00-9:45)'), ('3', 'Bloque 3 (10:15-11:00)'), ('4', 'Bloque 4 (11:00-11:45)'), ('5', 'Bloque 5 (12:00-12:45)'), ('6', 'Bloque 6 (12:45-13:30)'), ('7', 'Bloque 7 (14:15-15:00)'), ('8', 'Bloque 8 (15:00-15:45)')], help_text='Seleccione el bloque horario para la reserva', max_length=2)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accesos', to=settings.AUTH_USER_MODEL)),
                ('sala', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accesos', to='reserva_sala.sala')),
            ],
            options={
                'unique_together': {('usuario', 'sala', 'fecha_reserva', 'bloque_horario')},
            },
        ),
    ]
