# Generated by Django 5.1.6 on 2025-03-01 23:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reserva_sala', '0002_remove_usuario_apellido_remove_usuario_nombre_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accesosala',
            options={'ordering': ['-fecha_reserva', 'bloque_horario']},
        ),
    ]
